### ISSUE TITLE
gives warning if no record exists in datatable

### ISSUE THREAD

**Issue by credencysrajesh** [kEpEx/laravel-crud-generator#3] opened 2016-04-11 11:52 UTC
when i have no record in the table then it given warning of ajax_error  image is attached
![screenshot from 2016-04-11 17 21 50](https://cloud.githubusercontent.com/assets/11571617/14426102/fa7087ee-0009-11e6-8762-24260ee71b8d.png)

**Comment by kEpEx** [comment] 2016-04-11 23:33
Can you provide the response from your network tab. I am unable to reproduce it.

**Comment by credencysrajesh** [comment] 2016-04-12 04:32
issue resolved 

the issue was the primary key which is taking column name by default id so i got the resolution.

but now

i want make search which can search in all columns of datatable??

**Comment by kEpEx** [comment] 2016-04-12 04:34
@credencysrajesh  you can modify the SQL code in the controller of the screen to look for more columns. Please close the issue if resolved  :)

**Comment by credencysrajesh** [comment] 2016-04-12 04:36
i know but that is not proper way it should like yii search in model we can define search criteria and call that in controller

**Closed as completed** 2016-04-26 16:58 UTC
